---
title: "Education & Experience"
format: html
toc: true
toc-expand: 3
---



# Education

## Degrees

::: {.two-col}
<div>**University of California, Los Angeles**</div>
<div>*(3.993 GPA)*</div>
:::
::: {.two-col}
<div><small>Expected March 2026</small></div>
<div></div>
:::

  - **Psychology, B.A.**  
  - **Statistics & Data Science, B.S.**  
  - *Educational Studies Minor*



## Skills & Coursework

  - `R` and RStudio
    - `ggplot2`, `tidyverse`, `mlr3`
  - Psychometric Measure Development/Assessment
  - Multivariate Statistical Analysis
  - Quasi-Experimental Methods
  - Educationa Program Evaluation
  - Predictive Regression Modeling Methods
  - Familiarity with Bayesian Statistical Methods
  - Familiarity with $\LaTeX$, Quarto, Python, SQL





<div style="height: 20px;"></div>
# Selected Experiences

::: {.two-col}
<div>**mHTI Project Data Prep Team**</div>
<div>Oct. 2024 – Mar. 2025</div>
:::
::: {.two-col}
<div>*Fellowship (Short-Term)*</div>
<div>*Los Angeles, CA*</div>
:::

- Processed and cleaned qualitative data from multi-participant conference audio and video recordings to construct transcripts with detailed speaker identity information to enable more detailed further research analysis.  
- Utilized advanced transcription software and cloud-based file sharing platforms to efficiently manage, organize, and analyze large volumes of sensitive qualitative data while maintaining data-privacy standards.  
- Addressed technical challenges in audio quality and speaker overlap, developing solutions to improve transcript accuracy and completeness for downstream research applications.
- Maintained detailed documentation and records to ensure coordination of goals and workload among asynchronous teammates in remote work environment.


<div style="height: 20px;"></div>
::: {.two-col}
<div>**Team Lead**</div>
<div>May 2024 – Present</div>
:::
::: {.two-col}
<div>*Cathy's Cookies*</div>
<div>*Orange, CA*</div>
:::




